### ISSUE TITLE
Cannot Add Package via SPM in Xcode 15 Beta 3

### ISSUE THREAD

**Issue by TheOtherJFK** [MagicTimerFW/MagicTimer#21]
Hi! Thanks for the work you've put in to maintaining this library, I know it's going to save me a ton of time.

**Summary**
- Cannot add version of MagicTimer via Swift Package Manager
- Error SPM: `Failed to resolve dependencies Dependencies could not be resolved because package 'magictimer' is required using a stable-version but 'magictimer' depends on an unstable-version package 'magictimercore' and root depends on 'magictimer' 2.0.1.. <3.0.0.`

**Environment**
- Xcode Version 15.0 beta 3 (15A5195k)
- Build target iOS 17+

**Comment by sadeghgoo** [comment]
Thank @TheOtherJFK for opening this issue, I will fix it soon.

**Comment by sadeghgoo** [comment]
@TheOtherJFK  To continue your development checkout below link:
[https://forums.swift.org/t/dependencies-could-not-be-resolved-because-package-yeelampa-is-required-using-a-stable-version-but-yeelampa-depends-on-an-unstable-version-package-requester-and-root-depends-on-yeelampa-0-1-0/53840](https://forums.swift.org/t/dependencies-could-not-be-resolved-because-package-yeelampa-is-required-using-a-stable-version-but-yeelampa-depends-on-an-unstable-version-package-requester-and-root-depends-on-yeelampa-0-1-0/53840)

use latest commit hash to reference correctly and I will fix it soon.
commit hash: 9ff923bdea4b4dcfbca2002ff8b71ed7971f04d3
